<?php $this->load->view($hero); ?>
<?php $this->load->view($service); ?>
<?php $this->load->view($blog); ?>
<?php $this->load->view($project); ?>
<?php $this->load->view($cta2); ?>
<?php $this->load->view($about); ?>
<?php $this->load->view($cta1); ?>
<?php $this->load->view($donation); ?>
<?php $this->load->view($story); ?>
<?php $this->load->view($team); ?>
<?php $this->load->view($video); ?>
<?php $this->load->view($brand); ?>
<?php $this->load->view($testimoni); ?>
<?php $this->load->view($faq); ?>
